name: Upload to S3

on:
  push:
    branches: [ main ]

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::831926612453:role/s3-github-oidc
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          aws s3 cp ./ my-bucket-oidc2411/ --recursive
